theme: minima
#remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
title: Kandraisme
description: a jobless person who learn something new
#domain: kandraisme.github.io
url: https://kandraisme.github.io
#baseurl: /
